### ISSUE TITLE
Admin area speed of loading

### ISSUE THREAD

**Issue by lordmatt** [PressForward/pressforward#1054]
Just an FYI on my own testing. I installed on localhost and then left it alone for about four weeks. When I came to view the admin area again the load time was painfully slow. Taking minutes to reach the loading bar after which things shuffled along at a slow but acceptable pace.

- WP: 5.2.3
- OS: ubuntu 16.04 - 64-bit - 16 GiB RAM
- mysqli: 5.7.27-0ubuntu0.16.04.1
- Server architecture: Linux 4.4.0-159-generic x86_64
- Web server: Apache/2.4.18 (Ubuntu)
- PHP: 7.0.33-0ubuntu0.16.04.6 (Supports 64bit values)

My guess was that it used the call to load the admin area to run background tasks. However, there was still a substantial delay on the next viewing of the admin area.

I profiled load time with Chrome:

- Queued at 0
- Started at 4.37 ms
- Queueing 4.37 ms
- Stalled 2.35 ms
- DNS Lookup 6 μs
- Initial connection 0.11 ms
- Request sent 58 μs
- Waiting (TTFB) 38.33 s
- Content Download 13.61 s
- **Total time: 51.95 s**

**Overview**: Finish 2.9 min; DomContentLoaded 52.26s; Load: 52.55s

**Comment by AramZS** [comment]
@lordmatt is this the standard admin area or the PressForward admin area and does your system rely on standard wp-cron or do you have a traditional cron task hitting your wp-cron?

**Comment by boonebgorges** [comment]
I've had extensive problems with pageload time in the admin, and in my tests I've narrowed it down to the `show_embed()` support:

https://github.com/PressForward/pressforward/blob/babfba58a1adbf8bf03ed1bcef9c287b3e19a118/Core/Admin/PFTemplater.php#L625
https://github.com/PressForward/pressforward/blob/babfba58a1adbf8bf03ed1bcef9c287b3e19a118/Core/Admin/PFTemplater.php#L892
https://github.com/PressForward/pressforward/blob/babfba58a1adbf8bf03ed1bcef9c287b3e19a118/Controllers/PF_Readability.php#L369

See #888, which I think is the same issue.

I'm not 100% sure what this embed call is supposed to do  - see a79f70de687a569c532aa8f692756fb8d049d80a for a description in the commit message - but at the very least, the `wp_oembed_get()` response should be cached aggressively.

**Comment by boonebgorges** [comment]
Since roughly version 5.2.0, we've made a number of changes that have had a huge effect on All Content/Nominated load time:

- Caching for oEmbed fetches
- Delayed image loading #1114 
- Only attempt to fetch oEmbed markup for an item if the URL looks oEmbed-capable 

Both All Content and Nominated load in 1-2 seconds, while previously they took from 10-30 seconds.

Nominated before:
![nominated-before](https://user-images.githubusercontent.com/246627/221601372-49e15133-a559-43ba-8993-fd180d43ae43.gif)

Nominated after:
![nominated-after](https://user-images.githubusercontent.com/246627/221601415-a3d74528-b490-42ec-945d-c09aa24f7481.gif)

All Content before:
![all-content-before](https://user-images.githubusercontent.com/246627/221601449-dee0186d-3367-4510-8681-b7a172064715.gif)

All Content after:
![all-content-after](https://user-images.githubusercontent.com/246627/221601492-9fa6bf8c-8bca-4834-9090-30e7fe689058.gif)

As such, I'm going to mark this ticket complete. Further refinements will be handled in separate tickets.
