### ISSUE TITLE
Use Readability.js in Nominate This

### ISSUE THREAD

**Issue by boonebgorges** [PressForward/pressforward#1097]
Readability.php, even in its newer incarnations, has some limitations. See https://github.com/fivefilters/readability.php#limitations. Moreover, slow requests on the server cause render time to be extremely slow, which is a major usability time.

In the case of Nominate This, the only purpose for using Readability is to pre-populate the fields in the Nominate This window. This is all client-side work that could be done using JavaScript. As such, we would probably be better served by using Mozilla's JS library in Nominate This, rather than the PHP fork.

**Comment by boonebgorges** [comment]
I've completed initial work on this task.

I'd initially hoped it would be possible for the Nominate This client code to fetch the remote content and then parse it in the bookmarklet using Readability.js. After some testing, it's apparent that this kind of cross-domain request is not possible for many or most source sites, either because of restrictive CORS configurations or a lack of CORS at all. As such, it's necessary for the initial page fetch to be handled by a proxy client that's not subject to security restrictions in browsers. For PressForward, this means the WP server. As such, the new system does the following:

1. When the Nominate This window loads, it sends an AJAX request to the server asking it to fetch the content of the requested URL.
2. The URL content is fetched by the server (using WP's native HTTP API; see #1135)
3. The server responds to the AJAX request with a JSON object that includes the entire markup of the fetched page.
4. The Nominate This client JavaScript then uses Readability.js to detect the "readable" content, and inserts it into the editor.
5. Other fields in the Nominate This interface are processed in the client, rather than on the server: 'Author' is detected by Readability.js, while 'Tags' and 'Featured Image' (not visible in the interface, but stored anyway) is parsed using similar logic to what previously existed on the server.

Several immediate advantages:
* The Nominate This window loads and renders immediately. Previously, rendering was blocked by server-side requests for the source page. (That's *requests* plural - see #1094 and related tickets.) Now, the window is loaded instantly, and content fetched asynchronously (and only once). This difference is especially noticeable when the source site takes a long time to respond - see the washingtonpost.com gifs below.
* Related, the fact that we're loading asynchronously means that we can provide some status updates to the user. I've added a yellow "Loading..." notice whenever the request takes more than 2 seconds. See the washingtonpost.com example below. In cases where the server-side request fails for some reason, I also provide a similar red error message; in contrast, failed requests would sometimes result in fatal errors on the previous system, as you can see in the washingtonpost.com examples.
* As expected, the Readability.js library is better at parsing at least some content. In my testing, I came across some instances where PF was previously getting only an excerpt, while the new system was fetching the whole post content. In other cases, PF was previously including navigation elements, while the new system was properly excluding them. There are likely to be cases where the old system parses a piece of content in a way that we find "better", but with any library there are trade-offs.

A few before-and-after gifs that demonstrate the differences between the old system and the new one.

First, a single post from WordPress. Before: 
![wordpress-before](https://user-images.githubusercontent.com/246627/221005525-2f3f6277-5852-48e2-9a3c-d3b4177ece1c.gif)

After: 
![wordpress-after](https://user-images.githubusercontent.com/246627/221005592-0bc908f0-ef06-4453-afde-9df3037bb5be.gif)

Parsing is pretty much the same. The main difference is in the immediate window load: there's a blip during the "before" gif where rendering pauses while fetching the source content. In the "after" gif, this loading happens asynchronously.

Next case is an article from the New York Times. Before:
![nyt-before](https://user-images.githubusercontent.com/246627/221005949-9f101918-6a40-44da-9ea9-ea00c671d959.gif)

After:
![nyt-after](https://user-images.githubusercontent.com/246627/221005981-2930986a-9714-45fd-8ff5-cfdbb3757947.gif)

Here you can see some more significant improvements. In the Before gif, the window loads slowly. PF can't find the author. And the body text is not parsed particularly well: the interactive/graphic elements from the source (https://www.nytimes.com/interactive/2023/02/23/world/russia-ukraine-geopolitics.html) are partially detected and rendered. In contrast, the After gif shows that the window loads instantly, PF identifies the author, and the more decorative/interactive elements from the page are properly excluded.

Finally, a case from washingtonpost.com (source https://www.washingtonpost.com/politics/2023/02/22/arizona-election-fraud-claims-mark-brnovich/). Before:
![wapo-before](https://user-images.githubusercontent.com/246627/221007363-5617982e-13b3-43f5-9df9-7879410f6536.gif)

After:
![wapo-after](https://user-images.githubusercontent.com/246627/221007377-31c74b85-e20e-4d30-acf2-c14854b7ef93.gif)

The Before gif shows an almost unusable interface. It takes more than 30 seconds for the sidebar to appear. The main body content takes another 30 seconds. No author is identified, and only an excerpt is found. In contrast, the After gif quickly sees that the request will take more than a second or two (as washingtonpost.com requests always do, for whatever reason), so it shows the yellow 'Loading' notice. After several seconds, it receives its response, which includes the full body text and the Author info properly parsed.

So I think this is a pretty promising start. I'll keep the ticket open for feedback, and for cleanup as I continue to work on the release.

**Comment by AramZS** [comment]
This is such a great idea! I think this makes a ton of sense. 

I'll note that we did extensive experimentation to try and deal with the CORS issue and the possibility of presenting the window inside the top window instead of in a popup. Consistently, this caused significant issues that have only become more challenging. The security barrier for bookmarklets is much higher than it used to be, what they can do on and to the page has become progressively more limited, to the point that the use of bookmarklets is practically dead across similar services. Additionally, when we tried to float the Nom This window above the site in the window.top frame we saw that this also encountered security issues and some significant problems when the site was using a system that did not work like a normal DOM, including those that leveraged hydration techniques and basically any client-side React. 

The solution for this is supposed to be the extension, but it ran into its own significant challenges. Not least of which is that while the bookmarklet works on a mobile device, extensions don't. In the modern web I think the right solution for mobile is likely a Web App of the type we've seen popping up elsewhere, which can be installed via a browser action and can then have access to mobile devices' Share functionality. 

The one tripping point I'll note here is that to be careful that the HTML is as stripped down as possible. I think I recall us doing some hacking around the Readability setup because it had a tendency to let through things which either broke the nomination UI or the published article if we set the boundaries around the content it included too low, and excluded too much content when the readability setup had boundaries that were set too high (which may be what you are seeing in the last example).
