### ISSUE TITLE
Filter by Drafted

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#434]

**Comment by AramZS** [comment]
Hey @boonebgorges - Do you think you can take this on in the next week or so?

**Comment by boonebgorges** [comment]
Sure thing. Sorry this fell through the cracks.

I've started building something, but I'm at a bit of an impasse. In order to filter feed items by those that have drafts, I need to (a) grab a copy of all drafts, (b) figure out the feed item that each draft belongs to, and then (c) pass a list of those feed item IDs to `post__in` in the relevant places. From what I can tell, drafts are linked to feed items via the 'item_id' metadata, and `item_id` is built as a md5 hash of the URL and title of the original item. Is this correct? If so, I'm not sure how I'll be able to convert draft IDs to the corresponding feed item IDs. Unless maybe this hash is stored with the feed item itself as well? Is that the purpose of 'origin_item_ID'?

**Comment by AramZS** [comment]
Yes and yes. All items in the system should have `item_id` as the unique hash id. Additionally, nominations have the `origin_item_ID` which should be the Feed Item ID. Does that make sense and is useful?

**Comment by boonebgorges** [comment]
Thanks, that's helpful. 

This feature is ready to test in the 3.7.x branch.

**Comment by regan008** [comment]
I've tested it and found no issues so I'll go ahead and close it.
