### ISSUE TITLE
Nominate This should be updated 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#448]

**Comment by boonebgorges** [comment]
The new ("new") Press This is dramatically improved over the original version that was forked for Nominate This. Let's port it over https://github.com/WordPress/press-this/blob/trunk/class-wp-press-this-plugin.php

**Comment by boonebgorges** [comment]
Something to look at here is that, on some sites, the generic uglified variable names (like `var d = document`) result in conflicts with JS on the source site. We might think about a unique prefix, if Press This doesn't already do it.

**Comment by boonebgorges** [comment]
Press This does indeed have a dramatically better interface. But it still uses TinyMCE, and is essentially a fork of WP's "classic" editing experience. As such, even the new Press This interface is already obsolete. As such, I've decided to postpone major overhauls of the Nominate This window until we can move it over to the block editor. See #1124.

Instead, I've made a number of incremental improvements to the Nominate This window:

- The old Press This had its own media buttons. These buttons have been broken in PF for a long time, resulting in some very odd behavior. I've removed them and replaced them with the standard WP 'Add Media' button. In order to protect potentially sensitive content, I've added some filters ensuring that when a non-Editor/Administrator user clicks this Add Media button, they see only the items that they themselves have uploaded to the Media Library.
- I've slightly increased the default size of the Nominate This window, and resized the internal elements to make better use of the space. This change also means it will resize more intelligently on mobile devices.
- I did extensive cleanup of the nominate-this-core code, which included a lot of stuff that had been copied from the old Press This but was not used in PF. This also involved taking inline scripts and styles and moving them into the Webpack workflow, which will improve performance and cache-busting by loading assets as separate static files.

Screenshots:

![nomthis-before](https://user-images.githubusercontent.com/246627/236038359-65766739-6272-4534-a425-3b16dd680129.png)
Before

![nomthis-after](https://user-images.githubusercontent.com/246627/236038410-2dc6e67f-9c00-44ad-bdd1-1ac9b769f9a0.png)
After

Aside from bugs, I don't plan to make any more changes to the Nominate This window until and unless we convert it to use the block editor.

I'll keep this ticket open so that I can have a closer look at improvements that the new PressThis makes to the bookmarklet code.

**Comment by boonebgorges** [comment]
I've looked at the bookmarklet improvements in PressThis and I'm going to decide not to merge any of them. Most of them have to do with improved parsing of source content, but since we're now using Readability.js for this, it's mostly unnecessary. Plus, I'm having a hard time making the script compile in such a way that it doesn't render the source-content window as a boolean `true` or `false`. So I think it's not worth the effort at this time.

**Comment by boonebgorges** [comment]
I've added the `pf` prefix to all bookmarklet variables in c53a93b, to avoid the problems described in https://github.com/PressForward/pressforward/issues/448#issuecomment-1516705122

This is the extent of the action I'll take on the current ticket at this time.
