### ISSUE TITLE
Feature Request: manual feed update?

### ISSUE THREAD

**Issue by kaichi** [PressForward/pressforward#467]
Hello,

I'd like to make a suggestion for a feature request. I've noticed that when I add an RSS feed that contains older posts; say for example I add the RSS feed today and the last posts from December 15th don't show up on All Content. It would be nice to have a feature where you can go into Subscribed Feeds and manually bring in RSS items from specific feed -or- force check all feeds for items that PressForward hasn't brought in.

**Comment by AramZS** [comment]
Let's say a feature request here: manually refresh a feed.

**Comment by AramZS** [comment]
Feature request: Manually refresh a feed - ignoring date limit

**Comment by AramZS** [comment]
Refresh conditions:

Clicking the refresh links will only cause a refresh under the following conditions:

1. A feed chunk is not actively open
2. The feed retrieval process is not in the midst of attempting to
determine the next feed to chunk.
3. The feed being manually refreshed was neither just retrieved or the
previous feed retrieved as part of the retrieval process (in order to
avoid duplicated content caused by the feed being retrieved twice
simultaneously)
