### ISSUE TITLE
unexpected T_PAAMAYIM_NEKUDOTAYIM

### ISSUE THREAD

**Issue by michalkopanski** [PressForward/pressforward#472]
Hi there, I get a fatal error when I try to activate PressForward on a fresh install of latest Wordpress. I have no other plugins running at the moment, and I'm using the default theme.

Here's the error I get:

`Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in redacted/wp-content/plugins/pressforward/includes/slurp.php on line 501`

Best,

Michal

**Comment by AramZS** [comment]
Hi @michalkopanski 

Hmmm, well, that code seems to work elsewhere, but it is not strictly the best it could be there's two issues I think that you are hitting here, the first is in our use of `::` which is the thing that `T_PAAMAYIM_NEKUDOTAYIM` refers to and the 2nd is in the ability of your server to parse it. 

I'll open up a new issue to deal with a more formal calling of that variable elsewhere, but for here I think the problem is in your version of PHP. It appears that your server may be running a pre-5.4 PHP instance. PHP has now advanced to 5.6 and the community stopped supporting 5.4 actively as of 3 months ago. 5.3 is no longer supported in any way by the PHP community, as of four months ago. WordPress tries to support all versions of PHP since the project's initiation, but for a variety of reasons, including our use of various complex Class Object mechanics like `::`, we require at least PHP 5.4. For security reasons at the very least. 

I may be wrong in my assumption, so, if you can confirm that you are running PHP >= 5.4 ( http://php.net/phpversion is useful for this) and still seeing this problem, then we can progress towards other solutions.

**Comment by michalkopanski** [comment]
Hey @AramZS,

Thanks for your reply. Looks like you're right (my bad for not checking before posting), and it's about time to update my MAMP.

Best,

Michal
