### ISSUE TITLE
We need to call the Alert Box object's post_status more effectively

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#473]
As highlighted by the failure noted in #472 the call of the post_status string from the Alert Box object is not optimal and I suspect not formally correct. It resides at https://github.com/PressForward/pressforward/blob/master/includes/slurp.php#L501 and should be adjusted.

I believe that the optimal adjustment would be by providing an accessible function that returns that variable and then calling that function. @boonebgorges is there a better way to do it than that?

**Comment by AramZS** [comment]
@boonebgorges I wrote that function to fix this very problem. I'll switch it over, but is there no way to call a variable from inside the class without building a function to access it?

**Comment by boonebgorges** [comment]
Sorry for the delay. My wife had a baby on Tuesday, so I've been busy :)

> but is there no way to call a variable from inside the class without building a function to access it?

Two points. 

(1) Yes, there are two ways, depending on whether it's a static property: `$foo->bar` or `$foo::$bar`. The problem is that the latter syntax is invalid on PHP < 5.3. So the only ways to reference a static object property on these versions of PHP is to (a) build a getter method (like your `status()`) or to instantiate the object and reference it as a non-static property (`$the_alert_box->status`).

(2) More generally, it's good OOP practice to provide public methods for accessing object properties, because it makes it possible to restrict direct access to those methods at some later date should the situation arise. It's part of the principle of object encapsulation, which says that objects ought to be very limited in the way they interact with each other - limits that should be set by the public methods available on the object.

**Comment by AramZS** [comment]
@boonebgorges I figured, no worries. Congratulations! 

Ok, that makes a lot of sense. Thanks! 

Then the commit  19ea783 fixes the issue and closes this topic.
