### ISSUE TITLE
Deleting a subscribed OPML file does not delete the folder or the feeds

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#604]
@AramZS  @lmrhody  Should deleting a subscribed OPML also delete all the associated feeds and the folder they were stored in? I think I would expect that if I delete the OPML in the Add Feeds panel that the associated feeds would also be deleted.

**Comment by AramZS** [comment]
Oh, no it does not. I can look into that, but that is not currently an expected behavior.

**Comment by regan008** [comment]
This works but there seems to be a permission issue. I get an error message that reads "You are not allowed to delete this item" for any feeds that I did not add.  Even though I get this error the feed still deletes and is not there when I return to the dashboard.

**Comment by AramZS** [comment]
Wait... there shouldn't be any subscribed feeds under an OPML folder that you didn't add, how does that happen?

**Comment by regan008** [comment]
I think it has to do with user permissions, I should have clarified that.  So if pfadmin1 subscribes to an opml and pfadmin2 tries to delete it, it generates an error message

**Comment by AramZS** [comment]
But they both have full admin privs and should be able to delete everything right?

**Comment by regan008** [comment]
Yes both have full admin privs

**Comment by AramZS** [comment]
Testing this will require new nominations.

**Comment by AramZS** [comment]
This should occur properly now. I'm still having trouble causing this specific error. Perhaps I've eliminated it?

**Comment by regan008** [comment]
@AramZS I'm still getting an odd error that just says "You are not allowed to delete this item." It seems to be happening when I delete the opml parent and its child feeds at the same time.

**Comment by AramZS** [comment]
@regan008 Oh, I know what the problem is. You are deleting the OPML file first, which removes all the child feeds, but the command to delete the child feeds is still queued for execution, when it occurs, there is no longer a feed that can be deleted. I wonder if that is also the admin1 vs admin2 error we're seeing.

**Comment by AramZS** [comment]
Ok, this isn't really an execution problem, but a UX problem. Should we hide the subject feeds in the trash some way? Silently cause it to fail? Provide some other feedback?

**Comment by regan008** [comment]
@AramZS ah that makes sense. Hmm, I'm torn on what the best way to handle is. What would be easiest from a code perspective? I think hiding the subject feeds could be potentially confusing -- would it be super difficult to have it silently fail?

**Comment by AramZS** [comment]
@boonebgorges Hey, we could use your help or suggestion for this one:

It seems like our best bet might be to create a site option to activate on the start of the deletion process on Empty Trash:
 - To store as a site option that we are in the OPML deletion process and the set of OPML child Feeds that have been deleted
 - On delete attempts check against that option and decide if a delete actually should take place 
 - If it is in the set of IDs and the OPML deletion process is being executed inside this AJAX request, don't try to delete them. 
 - On AJAX return, clear the site option.

Is this the most effective way to solve the problem we've been discussing? If so, is there a best place to hook this process? I'm not sure how to monitor the AJAX action and understand when it is over from a hooked filter or action.

**Comment by AramZS** [comment]
Hmmmm.... additional problem discovered: if there are a lot of child feed items the Trash action seems to hang because it takes so long. 

Perhaps it might make sense to create a new button, remove the existing one, new AJAX action, and just cut off this whole process?

**Comment by boonebgorges** [comment]
Trying to wrap my head around this a little bit. My initial impression is that when you've indicated that you want to delete an OPML, triggering the deletion of child feeds, the system should be smart enough not to try to delete any child feeds independently. Whether that happens in the interface (grey out child feeds when an OPML is selected for deletion) or on the server (ignore child feeds if it's detected that the delete request includes an OPML), I'm not sure. Can you give me some more detailed instruction on how to reproduce? Do I need to be on the 3.6.x-opml-subscribe branch? Do you have a public OPML file you're using for testing? Does deletion happen on the Subscribed Feeds panel?

**Comment by AramZS** [comment]
Sample OPML file - https://dl.dropbox.com/s/fofo6bmx3tu73hn/blogroll.opml?dl=0
We're on 3.6.x now. 

Ok, events that occur to cause a problem:
 - Subscribe to OPML feed
 - Retrieve Feeds is triggered, it adds feeds to the system as Children of the OPML feed. 
 - User adds OPML feed to Trash
 - PF detects this action (hooked on to wp_trash_post)
  - PF adds all feeds to Trash that are children of the OPML file.
 - User goes to trash and presses Empty Trash button. 
 - System queues all current items to be trashed. 
 - System goes to delete OPML file
  - PF detects delete and deletes all child feeds, their child feed_items, and any empty folders created by the OPML file. 
 - System continues on to deleting the feeds
 - Feeds are already gone, system throws failure message. 

The problem being that PF needs to go through the deletion of children process if someone deletes just the OPML file, or if someone hits the Empty Trash function, but the current set up can't work both ways.

**Comment by boonebgorges** [comment]
Thanks very much for the details, @AramZS.

I've spent a bunch of time thinking about it and my conclusion is that this is a pretty ugly issue :) There are a couple things going on.

One is the concurrency issue you describe. PF's delete-feeds-of-opml and delete-items-of-feed routines take a long time to run, and emptying the trash (or any other actions that you perform on the affected items in the meantime) are going to cause problems.

But this all boils down to the real problem, which is that deletion takes a long time. Deleting an OPML file with 5 feeds, if each of those feeds has 10 items, means deleting 56 items. And these numbers are extremely conservative. In my local installation, where I (intentionally) have rather modest server settings, I was getting PHP fatal errors due to timeouts when bulk deleting just two or three feeds (which had a lot of items), to say nothing of Empty Trash or larger bulk deletions.

The most elegant fix would be batch deletion, similar to the batch RSS fetch. So, when you hook to `before_delete_post` or `wp_trash_post`, you'd traverse the hierarchy (feeds-of-OPML and items-of-feed), but instead of immediately deleting, you'd create a queue of IDs. Then you'd delete them in batches. This, by itself, is not too hard to do - it could share a mechanism with RSS fetching, or it could even be something simpler, hooked to 'admin_init' or whatever. 

But there are going to be interface issues, and WP doesn't make it easy to work around them. Let's say I delete an OPML subscription with Feed A, Feed B, and Feed C, and each of those has items A1-A10, B1-B10, C1-C10. If I delete the OPML subscription, PF will queue these other 33 post IDs for deletion on subsequent pageloads. But this means that if you go to view Trashed posts in the meantime, you'll see the to-be-deleted posts; performing bulk actions on them will cause the same problems described in this ticket. I think we can work around this problem with a 'pre_get_posts' filter that compares against the stored queue, making sure that items queued for deletion never appear in wp-admin list tables.

But this still leaves the problem of the Empty Trash button. When you click it, WP does a direct database query to get a list of posts that match the post_type/post_status, and then it calls `wp_delete_post()` on each one. There's currently no way for a plugin to intercede, either in the bulk delete or in `wp_delete_post()`, to tell WP not to delete a given post. I guess I'd be OK advocating for a WP hook of this sort - like maybe a `'pre_delete_post'` filter - if we thought that was a good way forward.

What do you think, Aram? If you think this sounds promising, I can see about building a proof-of-concept.

**Comment by AramZS** [comment]
I think that's a great idea on all counts. Go for it, I can't wait to see what you come up with.

I was originally thinking about batching AJAX requests, but that would require the user to sit around and this is a way better approach. Between now and the potential solution for the Empty Trash button though, replacing it with a different button might be the way to go, to insure that no errors are thrown in the mean time. We already have a few javascript hacks running on that page, so it might make sense, at least for now. What do you think?

**Comment by boonebgorges** [comment]
fa227c8 contains an inital pass. Some comments:

* I didn't understand the purpose of the `removed_{$type}` post status, so I ignored it. Thus, when deleting an item, the item itself is deleted in addition to its hierarchy tree. If the `removed_` post status is important, I can add it back in, though it complicates things.
* I've removed the `readability_status` checks. Post attachments are always deleted.
* There was a logic error in the previous code to delete post attachments, at least if I'm undestanding the inline comments correctly. (Namely: when an image has been imported from a feed and added to a feed item, it should be deleted when the parent post is deleted.) I've fixed it to work this way.
* Deletion batches work just 2 items at a time, and then fire off another request. This number was low for testing, and can probably be safely bumped up to 5 or 10. See `pf_process_delete_queue()`.
* I'm hiding queued-for-deletion posts everywhere in the interface. This should fix most concurrency problems, as originally described in this ticket. However, Empty Trash will still cause problems. I opened a core ticket that would help to work around the issue https://core.trac.wordpress.org/ticket/32933

I wrote a bunch of unit tests that show the internal consistency of the new stuff, but I'm probably not the best person to test that everything's working as expected within typical user workflows. I'm happy to answer any questions or readdress any aspects of this in response to the team's feedback.

**Comment by AramZS** [comment]
@boonebgorges I think there is an issue with the `removed_` type status, though not one that need impact the code you've got here currently we also use the `thing_deleter` code for https://github.com/PressForward/pressforward/blob/3.6.x/includes/admin.php#L1632 an AJAX delete process for feed items. I failed to doc in code, so this one is on me. 

The reason for the post status is that we wanted to give admins the ability to delete both nominations and feed_items. However, our collection process would pick up those feed items again (or potentially a user could re-nominate a deleted item). Instead, we set a post_status of removed_feed_item or removed_nomination to indicate that the items had been removed (and not to show them to users) but to retain them in our system for the feed retrieval (and nomination) process to see, and know not to recreate, because matched item_ids were already in the DB. 

Now, we can recreate this process with a separate function just for that purpose, or perhaps, thinking about it now, it might make more sense to handle this completely differently, say with a long-term transient or something like that holding an array of item_ids to check against. What do you think?

**Comment by AramZS** [comment]
@regan008 Can you give a test run through the trashing and deleting of OPML subscriptions and their related feeds with Boone's new code? It is on a new branch -  604-tree-deletion. Assuming this functionality works to satisfaction I think the best solution now is to use it and rebuild the old function, but only for use with deleting Feed Items. We can pursue a better overall solution for how we deal with deleting things from subscribed objects in a future release, but I'd prefer to move forward on this 3.6.x.

**Comment by regan008** [comment]
@AramZS This seems to be working so far. I'm still testing it out (had to add new feeds and I'm waiting for them to populate) but I haven't had any problems in the two feeds I've tried.

**Comment by regan008** [comment]
@AramZS I haven't been able to replicate the error with this new code -- I'd say this is good to go for 3.6.x.

**Comment by AramZS** [comment]
Good, I will author a merge here and pull back in the old delete code, but only for AJAX feed-item use.

**Comment by AramZS** [comment]
@boonebgorges I'm moving the batch cleanup process to your new method do you think there would be any problems involved with it dealing with a much larger set of post objects? The process might select thousands of feed-items and queue them for deletion.  I've moved it in c760589.

**Comment by boonebgorges** [comment]
I was testing with hundreds of objects when I was building it, and I 
didn't run into any problems - scalability was the point :)

**Comment by AramZS** [comment]
@boonebgorges I figured, but I thought it might be wise to double check before we set up the system to be regular be sending blocks of 1 to 3000 items at it.

**Comment by regan008** [comment]
@AramZS I'm testing the delete functionality currently and when I hit "empty trash" with 1,689 and I keep getting an error that says "The server encountered an internal error or misconfiguration and was unable to complete your request." Do you think this is something to do with our server or with the code?  I'll try it on a local server next.
![screen shot 2015-07-28 at 11 09 18 am](https://cloud.githubusercontent.com/assets/4553057/8935232/b29ea812-3519-11e5-856e-0dffd186dba9.png)

**Comment by boonebgorges** [comment]
@regan008 What's the URL you see when you get the error? Are you only seeing that URL after a delay - like maybe there's a timeout? Are you able to enable WP_DEBUG for testing on this installation?

**Comment by regan008** [comment]
@boonebgorges I just went back to the subscribed feeds page probably 10min after it threw the error and all the feeds were deleted. There must have just been a delay while the system emptied the trash. Let me get a large number in the trash again and see if I can replicate the error to get you the url and the wp_debug message.

**Comment by boonebgorges** [comment]
Excellent. The fact that the posts ended up being deleted means that the 
background batch delete process is indeed working, even if there's a bug 
causing the first click to time out.

If there is in fact a memory timeout (which is what it sounds like), 
it'll be helpful to have any exact details you can provide, so I can try 
to isolate it. Thanks!

**Comment by regan008** [comment]
@boonebgorges Ok, so I tried it again with 642 feeds.  It took about 30 seconds and then it timed out and gave me the same Internal Server error.  Here is the url: http://pftesting.chnm.org/wp-admin/edit.php?s=&post_status=trash&post_type=pf_feed&_wpnonce=26d6c3f0d4&_wp_http_referer=%2Fwp-admin%2Fedit.php%3Fpost_status%3Dtrash%26post_type%3Dpf_feed&action=-1&m=0&delete_all=Empty+Trash&paged=1&action2=-1

I turned on wp-debug but didn't see any messages when I emptied the trash.  Does this help at all? If it would help I can create you a login for this test site.

**Comment by mAAdhaTTah** [comment]
Sounds like Apache thinks PHP timed out and returned the error screen, while PHP kept processing (which is why you see all the feeds deleted at the end).

**Comment by boonebgorges** [comment]
Agreed. I will look into this to see why the timeout is happening on 
that initial click. Amanda, can you give me the OPML(s) that you're 
using to populate your site with test data?

**Comment by regan008** [comment]
Sure, I've been using: 
http://www.inoreader.com/reader/subscriptions/export/user/1006046789/label/MS_OneNote
http://cms.iopscience.iop.org/alfresco/d/d/workspace/SpacesStore/cd5bdf75-3373-11df-afda-57ea8c8155d6/iopscience-opml.xml
http://news.bbc.co.uk/rss/feeds.opml (this one sometimes takes a while to load but when it does there are hundreds of feeds.)
