### ISSUE TITLE
Feed count in Folders area contains incorrect numbers.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#606]
The count of Feeds to which the taxonomy in the Folders menu has been applied isn't showing a correct number. If you go to Folders and look at each folder there are numbers in there that seem random, I'm not sure where those numbers are coming from or why, but they don't seem to match anything else going on in the system.

**Comment by AramZS** [comment]
Hey @boonebgorges, I'm pretty puzzled on this issue, I'm just not clear on where these numbers are coming from or how to get them to just be the number of feeds in that taxonomy. Can you take a look?

**Comment by AramZS** [comment]
It may have something to do with how feeds are deleted, not sure.

**Comment by boonebgorges** [comment]
The numbers in the Count column are populated directly from the `get_terms()` call in `WP_Terms_List_Table`. `get_terms()`, in turn, grabs the `count` value that's saved in the wp_term_taxonmy table. This count is calculated automatically by WordPress (on post save and a couple other places) using the 'update_count_callback' function registered with the taxonomy. In the case of 'pf_feed_category', no 'update_count_callback' is specified. Typically, in the case of a taxonomy associated only with a CPT, this will mean that WP will fall back on `_update_post_term_count()`. 

But because of the way you're registering the taxonomy - first with a blank object type https://github.com/PressForward/pressforward/blob/3.6.x/includes/class-pf_folders.php#L49 and only later associating it with 'pf_feed' https://github.com/PressForward/pressforward/blob/3.6.x/includes/class-pf_folders.php#L66, the object types associated with the `pf_feed_category` taxonomy end up as an array that looks like this:

    array(
        '',
        'pf_feed',
    )

As a result, this check is failing https://github.com/WordPress/WordPress/blob/4.2.2/wp-includes/taxonomy.php#L3670 (because `array( '', 'pf_feed' ) != array( 'pf_feed' )`), and `update_generic_term_count()` is getting run instead. It's likely that this is causing your problem, because `_update_generic_term_count()` simply counts relevant rows in wp_term_relationships, while `_update_post_term_count()` is sensitive to 'post_status' as well as 'post_type'.

In 62ef2f238e0 I specified that `_update_post_term_count()` should be used for updating counts for 'pf_feed_category'. With this changeset merged to your local, try modifying a couple posts, and see whether the counts for the corresponding folders correct themselves. I'm guessing they will :) If not, maybe you can give me a dump of your database, and I can try tracking down the problem more specifically.

**Comment by boonebgorges** [comment]
Part of this is, IMO, a bug in WP, so I'm going to put a fix in there. Still not 100% it'll fix your problem, but hey.

**Comment by boonebgorges** [comment]
https://core.trac.wordpress.org/ticket/32590#ticket

**Comment by AramZS** [comment]
Huh, interesting. Thanks @boonebgorges !

**Comment by AramZS** [comment]
So on this note, I think this is as fixed as it can be.

**Comment by regan008** [comment]
@AramZS This looks fixed to me
