### ISSUE TITLE
Nominate This button broken in WP

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#614]
The styling internally for the plugin as it relates to Nominate This is broken. The link appears without the button, and the margins are off. I think the indents were deleted or something...

**Comment by regan008** [comment]
@AramZS This didn't get tagged 3.7.x but is still an issue. Is this an easy fix before we release?  If not we can move it to 3.8 but since all of our screenshots and documentation show a button I can imagine this being slightly confusing.  Seems like maybe its just missing a css class or something? It has reverted to a link in both All Content and Tools. For reference it used to look like this: 

![screenshot 2015-11-15 10 57 01](https://cloud.githubusercontent.com/assets/4553057/11169499/ba9e5110-8b87-11e5-99c8-27598c97d508.png)
![screenshot 2015-11-15 10 56 55](https://cloud.githubusercontent.com/assets/4553057/11169500/baa3faac-8b87-11e5-84da-f640c303a030.png)

And now its just a link:
![screenshot 2015-11-15 10 57 21](https://cloud.githubusercontent.com/assets/4553057/11169496/b6c27968-8b87-11e5-8189-042d472d9091.png)

**Comment by AramZS** [comment]
@regan008 @lmrhody  Should be resolved now

**Comment by regan008** [comment]
@AramZS Looks good
