### ISSUE TITLE
Source link is not generated when content is nominated from the Nominate this bookmarklet

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#620]
This issue was submitted on the PF.org forums.  Here is a description of the issue: 

 It appears that when you submit a story via the PressForward DASHBOARD area it does NOT show the source link to the story at the bottom of the post content. BUT if you submit the story via the Nominate This bookmarklet it DOES automatically put the Source Link at the bottom of the post content. So it appears that there is possibly some kind of bug. (Unless I’m doing something wrong.)

Same issue here. Source not posting when I nominate to draft then post, or when I use amplify to send directly to draft then post.

See the discussion here: http://pressforward.org/forums/topic/would-like-link-back-to-source-in-the-body-of-the-message-like-wordpresss-press-this-does/

**Comment by AramZS** [comment]
Do any nominations through the dashboard add the source statement to the
bottom in the style of Nominate This? I didn't think we did that anywhere
but the bookmarklet.
On Jun 22, 2015 11:44 AM, "Amanda Regan" <notifications@github.com> wrote:

 This issue was submitted on the PF.org forums. Here is a description of
the issue:

It appears that when you submit a story via the PressForward DASHBOARD area
it does NOT show the source link to the story at the bottom of the post
content. BUT if you submit the story via the Nominate This bookmarklet it
DOES automatically put the Source Link at the bottom of the post content.
So it appears that there is possibly some kind of bug. (Unless I’m doing
something wrong.)

Same issue here. Source not posting when I nominate to draft then post, or
when I use amplify to send directly to draft then post.

See the discussion here:
http://pressforward.org/forums/topic/would-like-link-back-to-source-in-the-body-of-the-message-like-wordpresss-press-this-does/

—
Reply to this email directly or view it on GitHub
<https://github.com/PressForward/pressforward/issues/620>.

**Comment by regan008** [comment]
@AramZS Some do, some don't. I can't seem to figure out why some posts will generate the link and some won't.

**Comment by AramZS** [comment]
Is that the preferred behavior? The creation of the link at the end?

**Comment by regan008** [comment]
I think so. If it isn't there we end up adding one ourselves. It would be good if it automatically generated it universally.

**Comment by AramZS** [comment]
It does auto generate, (though it sometimes doesn't work, that's now resolved) but it only generates that link if the user isn't already forwarding users to the source. Is that acceptable? The assumption is that if you are set to forward, no one is going to make it to the bottom of the item.

**Comment by AramZS** [comment]
The exception is Nominate This, which *always* adds that source statement to the bottom, perhaps we want to change that as well? Control the whole thing with its own option?

**Comment by AramZS** [comment]
With commit ef82c68f1a03080a7d3b8054e1b78a284835c47a we assure that all posts will have the source statement attached.
