### ISSUE TITLE
server recommendations for pilot partners

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#621]
Can you quickly spec out what the optimal & tolerable server setup would be for running a mid-sized PF site?

**Comment by AramZS** [comment]
After some testing on various servers and more long term situations I have determined that:
1GB of RAM and at least 20GB of harddrive is a good place to be for a server. Using a single core (either in a dedicated or shared setting) should be sufficient. 

Users should have the level of access to their server that will allow them to create their own MySQL tables in the WordPress DB (which means a number of managed WordPress-only hosting solutions will not work) and the ability to access and set server-initiated cronjobs. 

In this, an AWS Mini, 10/mo Digital Ocean Plan or standard shared hosting plan for Dreamhost should be sufficient. 

However, if any other things are on the server, it may cause problems, and anything over a couple dozen feed subscriptions will cause serious issues on this configuration due to database activity and size. 

If the user is subscribing to more than maybe 12-24 feeds, then they will either need a heavier server, a VPS, a dedicated server, or they will need to host their MySQL database on a different server (WordPress explicitly supports this and server providers like DreamHost provide a method for making this functionality work fairly easily). MySQL for feed counts approaching a few hundred can take down a low level shared server and database size can ballon to a 1GBish. WordPress has such a low footprint it can be run on either the same or a different server than the MySQL, as long as server size and memory is sufficient. 

To deal with that size, I'd recommend either a server with at least 2 cores and 2GB of memory. This can be somewhat ameliorated by setting PressForward to shorter store-times from feed-items (a user setting), but even a month of 300-600 feeds is a lot of items in the database, but setting it that low can drop requirements down to the previous level. This is further altered if the readership is high, only in the sense that that acts as a multiplier for things like RAM requirements, but that's outside of our scope. 

Finally, the server should support the latest version of PHP (5.4 required for full functionality, 5.5 preferred) and the latest version of WordPress should be installed (3.4 is I think as low as we can go, 4.x+ preferred).

Does that work?

**Comment by lmrhody** [comment]
Has there been any further feedback on this @slwestcott ? Can we close this issue?

**Comment by slwestcott** [comment]
No further feedback since they submitted the budget, but no way of knowing if they have additional questions until they start launching their sites. However, I think this is perfectly sufficient for the time being and, yes, the issue can probably be closed.
