### ISSUE TITLE
Displaying Subscribed Feeds

### ISSUE THREAD

**Issue by devinbalkind** [PressForward/pressforward#630]
Hi.  I was wondering how to create a page that displays the feeds I'm subscribed to through PressForward.  Ex. http://digitalhumanitiesnow.org/subscribed-feeds/

Thanks!

**Comment by regan008** [comment]
@devinbalkind The subscribed feeds page on Digital Humanities Now is generated using a shortcode that is built into the [PressForward TurnKey Theme](https://github.com/PressForward/PressForward-TurnKey-Theme). You can download the theme and use: 
* [feeds="published"] to show active feeds
* [feeds status="alert_specimen"] to show alerted feeds
* [feeds status="draft"] to show broken feeds. 

If you'd like to build this into your own theme see lines 26-48 in [functions.php](https://github.com/PressForward/PressForward-TurnKey-Theme/blob/master/functions.php) in the PressForward TurnKey Theme repository. 

Let me know if you have further questions!

**Comment by devinbalkind** [comment]
Awesome.  I'm using your theme so that worked perfectly. Thanks!

Is there a list anywhere of the available shortcodes?

I'd like to put the posts index and the feeds index on the same page so is
there a post index shortcode as well that I could use?

**Comment by regan008** [comment]
Perfect, feel free to submit issues on the theme if you find bugs or have questions.

The post index page is actually a page template rather than a shortcode. The categories for each tab get set in the theme options.  Unless you want to edit the page template there isn't an easy way to get both onto the same page at the moment. You could put the shortcodes above the tabs but that is probably not ideal. Feel free to submit this as an issue on the theme and I might be able to get to it over the next month or so. It would be ideal for the post index page to be a shortcode and to be more customizable. Currently it isn't easy to change the number of tabs that appear but that should be at the top of the list for the next version.

**Comment by regan008** [comment]
Also, I thought the shortcodes were in the documentation but it looks like I missed that. I'll edit the documentation to include the shortcode over the weekend. Currently the feedlist is the only shortcode.

**Comment by devinbalkind** [comment]
Thanks so much for your amazing responsiveness.

Added the issue.  

While I have your attention I'd like to direct it briefly to [Page Builder] (https://wordpress.org/plugins/siteorigin-panels/) layout plugin, which is a remarkably stable layout builder that fits next to your Text editor in page/posts, has great import/export functionality and fully leverages WordPress widgets.  It's revolutionized the way I build sites, and made certain theme/plugin features less important (ex. many different page layouts, special front page layouts, etc) and other features super important (display widgets, more menu area).  

Anyway, just thought I'd bring that to your attention if it isn't already.

Thanks a bunch.  All the best.

**Comment by regan008** [comment]
@devinbalkind Thanks for suggesting Page Builder. It looks really flexible. I'll ensure that we are compatible as it looks like a great tool for those who want to adjust layouts in the theme.
