### ISSUE TITLE
Content sent to draft arrives as an empty container

### ISSUE THREAD

**Issue by eolson3** [PressForward/pressforward#646]
Not sure how else to describe it.  A user has emailed us with a problem wherein content sent from the nominated panel to draft arrives without any content or even a title; just a blank entry.  I haven't been able to recreate the issue on the test site.  Any ideas?  Should I get a list of other plugins that are active, perhaps?

Thanks,

Eric

**Comment by miobook1** [comment]
Yes, thanks. I've submitted issue because from nominated article to draft, when i goes to articles there are no metadata. No title, no images no text.

Now i can't also have view of the article feed :(

**Comment by AramZS** [comment]
Hi @miobook1 @eolson3 - I'm not super clear how this could happen, but it is possible that there is an unanticipated error in the content itself that is causing our processing of it to break. A list of plugins would be great, but it would be even better to get an idea of the feed this is happening on and particularly the pieces of content, to make sure the problem isn't there. 

Assuming it is not, we can then see if there is a plugin conflict or not.

**Comment by AramZS** [comment]
@miobook1 What do you mean by article feed?

**Comment by miobook1** [comment]
The feed list

Inviato da myMail per iOS


sabato 29 agosto 2015 20:15 +0200 da Aram Zucker-Scharff  <notifications@github.com>:

**Comment by eolson3** [comment]
@miobook1 Could you give us a list of the other plugins that you use?  There could be something conflicting with one of them.

**Comment by eolson3** [comment]
@miobook1 You can't see your subscribed feeds any longer?  But content is still being retrieved?  Does the same effect appear when sending content from multiple sources to draft?

Trying to narrow down the issue.


E

**Comment by miobook1** [comment]
Hi,

I can see the subscribed feeds now but it doesn’t work with the draft.

I’ve also canceled many plugins not useful, but the problem persists.

If you want I can give you access to admin panel in my wordpress site so you can see it.
Give me your email and i sent you an invite as administrator of the site.

Thanks


Nicola


----------------------
MioBook.
www.miobook.org

Il giorno 31 agosto 2015 @ 20:19:32, Eric Olson (notifications@github.com) ha scritto:

@miobook1 You can't see your subscribed feeds any longer? But content is still being retrieved? Does the same effect appear when sending content from multiple sources to draft?

Trying to narrow down the issue.

E

**Comment by AramZS** [comment]
@eolson3 Would you like to take on getting a login so we can examine the site in action?

**Comment by miobook1** [comment]
Ok, thanks a lot.

I’ve send an invitation as administrator from inside WP
----------------------
MioBook.
www.miobook.org

Il giorno 01 settembre 2015 @ 16:43:14, Eric Olson (notifications@github.com) ha scritto:

@miobook1

Let's try that. My email is eric@pressforward.org.

**Comment by miobook1** [comment]
Hi, I send you an invitation to my backend site in miobook.org

Did you receive my mail?

----------------------
MioBook.
www.miobook.org

Il giorno 01 settembre 2015 @ 18:10:11, MioBook. (miobook@yahoo.it) ha scritto:

Ok, thanks a lot.

I’ve send an invitation as administrator from inside WP
----------------------
MioBook.
www.miobook.org

Il giorno 01 settembre 2015 @ 16:43:14, Eric Olson (notifications@github.com) ha scritto:

@miobook1

Let's try that. My email is eric@pressforward.org.

**Comment by AramZS** [comment]
@eolson3 ^ ?

**Comment by miobook1** [comment]
Hi, I send you an invite to look at the issue on my wordpress site. Did you receive it?

----------------------
MioBook.
www.miobook.org

Il giorno 03 settembre 2015 @ 06:37:38, Aram Zucker-Scharff (notifications@github.com) ha scritto:

eric@pressforward.org

**Comment by eolson3** [comment]
@miobook1 Sorry for the delay; I have not received the invite.  Could you email me the credentials that you assigned, or perhaps try the invite again?

**Comment by miobook1** [comment]
www.miobook.org/wp-admin					

user: Eric

pssw: 4UM*OPpzcPN$366b2NyEoUBI

Thanks for your help!

----------------------
MioBook.
www.miobook.org

Il giorno 03 settembre 2015 @ 16:06:51, Eric Olson (notifications@github.com) ha scritto:

@miobook1 Sorry for the delay; I have not received the invite. Could you email me the credentials that you assigned, or perhaps try the invite again?

**Comment by eolson3** [comment]
Got it, thanks!

**Comment by miobook1** [comment]
I'm now using Safari, maybe the browser can be a reason of the issue?

**Comment by eolson3** [comment]
What were you using before?

**Comment by miobook1** [comment]
First Chrome, but I have problem because it doesn't load my site, so I tried Safari and everithing was going well, until the problem of not shown nominated and draft empty.

**Comment by eolson3** [comment]
@AramZS It looks like even the reader function is being blocked somehow.  The content actually begins to appear, then disappears and is replaced by the "Retrieving full article" text.  Nominating new items does not send it to the nominated list.  Sending to draft creates an "(Untitled)" piece of content with nothing else (eg. title, text, images, metadata).  I went through the plugins one at a time, but that didn't free it up.  There are some there that look like they could interfere, but perhaps it is a combination.  I'll post a list of active plugins below.


Akismet
Blogroll widget with RSS Feeds
Categories to Tags Converter Importer
Content Egg
Editorial Assistant by Zemanta
Google AdSense
Iubenda Cookie Solution
MyThemeShop Theme / Plugin Updater
OPML Importer
Pixabay Images
PressForward
SumoMe
TinyMCE Advanced
Woopra
WP Google Images Search And Insert
WP Mega Menu
WP Review Pros
WP Scribe Box
WP Pro Subscribe
WP Tab Widgets
Yoast SEO

**Comment by miobook1** [comment]
eureka!!!!
Now i’ve deactivate Yoast plugin, and the draft is now correct. The problem is Yoast plugin conflict.

It’s a pity because Yoast so plugin is very good tool.

The problem in nominated persists, it doesn’t  create the nominated article in the list.


Il giorno 03 settembre 2015 @ 17:21:22, Eric Olson (notifications@github.com) ha scritto:

@AramZS It looks like even the reader function is being blocked somehow. The content actually begins to appear, then disappears and is replaced by the "Retrieving full article" text. Nominating new items does not send it to the nominated list. Sending to draft creates an "(Untitled)" piece of content with nothing else (eg. title, text, images, metadata). I went through the plugins one at a time, but that didn't free it up. There are some there that look like they could interfere, but perhaps it is a combination. I'll post a list of active plugins below.

Akismet
Blogroll widget with RSS Feeds
Categories to Tags Converter Importer
Content Egg
Editorial Assistant by Zemanta
Google AdSense
Iubenda Cookie Solution
MyThemeShop Theme / Plugin Updater
OPML Importer
Pixabay Images
PressForward
SumoMe
TinyMCE Advanced
Woopra
WP Google Images Search And Insert
WP Mega Menu
WP Review Pros
WP Scribe Box
WP Pro Subscribe
WP Tab Widgets
Yoast SEO

**Comment by miobook1** [comment]
No, i’m wrong the right draft is created by Eric…..I’m sorry


Il giorno 03 settembre 2015 @ 20:15:23, MioBook. (miobook@yahoo.it) ha scritto:

eureka!!!!
Now i’ve deactivate Yoast plugin, and the draft is now correct. The problem is Yoast plugin conflict.

It’s a pity because Yoast so plugin is very good tool.

The problem in nominated persists, it doesn’t  create the nominated article in the list.


Il giorno 03 settembre 2015 @ 17:21:22, Eric Olson (notifications@github.com) ha scritto:

@AramZS It looks like even the reader function is being blocked somehow. The content actually begins to appear, then disappears and is replaced by the "Retrieving full article" text. Nominating new items does not send it to the nominated list. Sending to draft creates an "(Untitled)" piece of content with nothing else (eg. title, text, images, metadata). I went through the plugins one at a time, but that didn't free it up. There are some there that look like they could interfere, but perhaps it is a combination. I'll post a list of active plugins below.

Akismet
Blogroll widget with RSS Feeds
Categories to Tags Converter Importer
Content Egg
Editorial Assistant by Zemanta
Google AdSense
Iubenda Cookie Solution
MyThemeShop Theme / Plugin Updater
OPML Importer
Pixabay Images
PressForward
SumoMe
TinyMCE Advanced
Woopra
WP Google Images Search And Insert
WP Mega Menu
WP Review Pros
WP Scribe Box
WP Pro Subscribe
WP Tab Widgets
Yoast SEO

**Comment by eolson3** [comment]
@miobook1 That's alright, I did think it was strange to see it work for you when I couldn't even get the reader to work properly.  Could we try deactivating all but PressForward?

**Comment by miobook1** [comment]
Yes, sure. 


Il giorno 03 settembre 2015 @ 20:20:04, Eric Olson (notifications@github.com) ha scritto:

@miobook1 That's alright, I did think it was strange to see it work for you when I couldn't even get the reader to work properly. Could we try deactivating all but PressForward?

**Comment by eolson3** [comment]
Ok, so that revived the nominated panel.  Sending to draft works on that route, and everything comes with it.  The amplify button route isn't working, but that isn't unique to you.  We're working on that.

Now I'm going to add your plugins one at a time until I hit a snag.  You're nominated list is going to be clogged up while I test this, but hopefully you're in the clear after that.

**Comment by miobook1** [comment]
Thanks!!!!

Can I reactivate the plugins?


Il giorno 03 settembre 2015 @ 20:44:09, Eric Olson (notifications@github.com) ha scritto:

Ok, so that revived the nominated panel. Sending to draft works on that route, and everything comes with it. The amplify button route isn't working, but that isn't unique to you. We're working on that.

Now I'm going to add your plugins one at a time until I hit a snag. You're nominated list is going to be clogged up while I test this, but hopefully you're in the clear after that.

**Comment by eolson3** [comment]
I'm doing that right now, but one at a time.  Maybe the issue will become apparent that way.  Is the reader working for you?  Is it retrieving text?

**Comment by miobook1** [comment]
Ah ok! I’ve tried to sent one article in nominated and doesn’t work, then to the draft and the issue persists just now…draft empty


Il giorno 03 settembre 2015 @ 20:52:21, Eric Olson (notifications@github.com) ha scritto:

I'm doing that right now, but one at a time. Maybe the issue will become apparent that way. Is the reader working for you? Is it retrieving text?

**Comment by miobook1** [comment]
Now it works, maybe i’ve not wait enough time he loaded the info of the article


Il giorno 03 settembre 2015 @ 20:55:05, MioBook. (miobook@yahoo.it) ha scritto:

Ah ok! I’ve tried to sent one article in nominated and doesn’t work, then to the draft and the issue persists just now…draft empty


Il giorno 03 settembre 2015 @ 20:52:21, Eric Olson (notifications@github.com) ha scritto:

I'm doing that right now, but one at a time. Maybe the issue will become apparent that way. Is the reader working for you? Is it retrieving text?

**Comment by eolson3** [comment]
Try it with content from a couple of different sources.  Maybe one of the feeds is funky.

**Comment by eolson3** [comment]
All of the plugins that were active when I began are now restored.  Seems like nominating and drafting are now working.  The reader DOES work for me when viewing nominated content, but not in all content.  That's weird, and let me know if that is still happening in a week or so, but you have regular functionality back.  I also made the custom metadata fields visible while in draft, but you can hide them again in the screen options (top right of the screen while in Draft).

Hard to tell what caused that in the first place, but it looks like you are good to go for now!  Let me know if it happens again.

**Comment by miobook1** [comment]
Thanks so much!
I’ll be in contact!


Il giorno 03 settembre 2015 @ 21:26:41, Eric Olson (notifications@github.com) ha scritto:

All of the plugins that were active when I began are now restored. Seems like nominating and drafting are now working. The reader DOES work for me when viewing nominated content, but not in all content. That's weird, and let me know if that is still happening in a week or so, but you have regular functionality back. I also made the custom metadata fields visible while in draft, but you can hide them again in the screen options (top right of the screen while in Draft).

Hard to tell what caused that in the first place, but it looks like you are good to go for now! Let me know if it happens again.
