### ISSUE TITLE
List view has blue linked Titles on a blue background.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#694]

**Comment by AramZS** [comment]
Resolved with https://github.com/PressForward/pressforward/commit/20ef124c01b8acc2369f0df1e924a5f3449871eb

**Comment by bschnei6** [comment]
List view now has blue linked titles on a white background. This issue can be closed.

**Comment by regan008** [comment]
Hey @AramZS, sorry I've been MIA for the last few weeks as I finished up some school stuff. I'm just now returning to 3.8 and testing it.  

I know we already closed this, but now that I'm looking at it more closely I'm wondering if it might look a bit better to make the `<div role="Main">` section rather than `<div id="entries">` (see screenshot) on All Content/Nominated white. I think the white helps visibility but adds yet another "box" to the All Content and Nominated pages and adds to the sort of uneven stacking of various elements.  What do you think?  See the screenshot below where I've changed it in the inspector. 
![screenshot 2015-12-14 13 52 05](https://cloud.githubusercontent.com/assets/4553057/11790568/79fa5c9a-a26a-11e5-8ebe-41c471e8dfea.png)
![screenshot 2015-12-14 13 51 43](https://cloud.githubusercontent.com/assets/4553057/11790575/875d7f5c-a26a-11e5-8855-618b8065ab5b.png)

**Comment by AramZS** [comment]
Sure, that works. My only concern is that it leaves our UI a little less distinct.

**Comment by AramZS** [comment]
Fix this to main instead.

**Comment by regan008** [comment]
@AramZS are we holding off on switching this to `<main>` for 3.8?

**Comment by AramZS** [comment]
@regan008 Nah, I just haven't hit this issue yet.

**Comment by AramZS** [comment]
@regan008 I couldn't apply the style and have it be aware of if we were in list or grid mode, so I applied it further up the chain, but a little lower than main, that should create the intended effect. Give me the heads up, but I think this works.

**Comment by regan008** [comment]
Ah, I see -- that makes sense. I hadn't thought about the difference between grid and list view.  Looks good for now.
