### ISSUE TITLE
What Rights on content interpret how we deal with that content?

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#702]
What metadata do we generate, how do we interpret it?

**Comment by lordmatt** [comment]
I know I am an outsider here but might first instinct would be to look to Creative Commons. They seem to have codified the basics of rights quite nicely. Attribution, commercial (or not), share-a-like, public domain, etc.. Working from the CC approach, it should be possible to generate a very concise summary that is easily machine-readable and yet human readable too. If you assume "fair use only" unless some obvious metadata indicates otherwise, it would be hard to go wrong.

**Comment by boonebgorges** [comment]
There's no way we can reliably decide the intention of the owners of the source content. Those who choose to use CC licenses might have machine-readable indicators of author intent (see eg https://wiki.creativecommons.org/wiki/RDFa), but then again they may not. 

In any case, the laws and mores around content reuse vary from place to place. PF isn't able to make those decisions. They have to be built into the editorial workflow for the specific project using PF.
