### ISSUE TITLE
Readability doesn't load

### ISSUE THREAD

**Issue by asmorton** [PressForward/pressforward#720]
Readability sticks at "Attempting to retrieve full article" on digitalhumanitiesnow.

**Comment by AramZS** [comment]
It doesn't load for users of the site or on articles on the site?

**Comment by asmorton** [comment]
our eds have to go directly to read original to get to items from all content/nominated

**Comment by asmorton** [comment]
Correction - it seems to work for items in nominated

**Comment by AramZS** [comment]
@asmorton I've checked in the site, the process is executing, the AJAX is firing and responding properly (so if you refresh the page after opening the item, you'll see the full readable post in place). It looks like it is just not placing the readability text in via AJAX. Has anything changed on the site recently? Is this since the PF upgrade?

**Comment by asmorton** [comment]
I've only noticed it since the PF update. Other than that, we haven't changed anything on the site.

**Comment by AramZS** [comment]
@asmorton Hey, I've put a bunch of work into optimizing this function. It should no longer be occurring with the latest version of PressForward. Is it?

**Comment by regan008** [comment]
@asmorton do we know if this is still an issue?

**Comment by jccatalano** [comment]
I have not been seeing this issue. Some feeds hang longer than others but they are loading.

**Comment by regan008** [comment]
Ok lets just close it. We can always reopen if it reappears.
