### ISSUE TITLE
PressForward is not properly detecting existing nominations where no item exists. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#885]

**Comment by jccatalano** [comment]
I nominated a post with one user using the bookmarklet. Then sent the same post two draft with another user using the bookmarklet. The nomination did not duplicate and the nomination count correctly indicated 2 nominations.

**Comment by jccatalano** [comment]
Of note, if I nominate a post from all content, and then nominate that same post from the bookmarklet, the post will duplicate in nominated.

**Comment by AramZS** [comment]
Related to #896, test and queued for patching

**Comment by regan008** [comment]
I found that the same user can duplicate a post. I nominated one item from all content and then, under the same user, nominated the same item from the bookmarklet. The post showed up in nominated two separate times. I then logged in as a contributor and nominated the same item with the bookmarklet. The nomination count increased on the first item nominated from all content. 

But I think that may be a separate issue. If a post does not exist in all content, and it is nominated by 2 different users the nomination count does indeed increase and there is no duplication. 

I'm going to close this and add the above as a separate issue because I think this is resolved.
