### ISSUE TITLE
Enhancement: JSONfeed

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#929]
Not currently an issue, but something to be aware of as purveyors of one of the best RSS reader/tools out there: https://jsonfeed.org/ is a new feed format in the last week. There's also a WordPress plugin for it ([GitHub](https://github.com/manton/jsonfeed-wp)), which is already in the [official repository](https://wordpress.org/plugins/jsonfeed/).

Several readers are already dogfooding the spec, but it's still evolving. If it seems interesting, it may be worth supporting, though I might recommend holding off a beat while things are still evolving with v1.0 and not many sites are providing these feeds for consumption (yet).

Additional resources:
http://indieweb.org/jsonfeed
http://inessential.com/2017/05/17/json_feed

**Comment by AramZS** [comment]
We attempted to support RSSJS, the previous spec in this style, but discontinued development when it was removed from WordPress Core. 

Since WordPress is 25% of the web, any feed format not supported by Core is unlikely to gain permanence. While we would accept a pull request to create support, I don't think we have any interest in supporting a late in the game RSS as JSON format that has no support or inclusion in WordPress Core.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/929#issuecomment-304474006" class="u-in-reply-to"></a>Mostly something to keep in mind, potentially for a year or so out if it ever gains traction. It's a possibility given these particular developers...
