### ISSUE TITLE
Conflict with Event Organiser Plugin

### ISSUE THREAD

**Issue by jeau** [PressForward/pressforward#931]
My Wordpress is up to date and I have installed the following plugins: PressForward 4.3.0  and [Event Organizer](https://wp-event-organiser.com/) 3.1.9.  @stephenharris

In the ical sync settings of Event Organizer, I find a reference to PressForward. Cf screenshot.
The automatic sync is broken, the manual (with Fetch now)  works fine. 

![capture d ecran 2017-06-05 a 17 25 05](https://cloud.githubusercontent.com/assets/3129299/26790904/b3618fc2-4a15-11e7-9335-5c3320f52e61.png)

**Comment by stephenharris** [comment]
@jeau PressForward appears because they have registered a wp-cron interval. So that is of no concern.

If manual sync is working but the cron isn't there can be two reasons for this typically. First the cron job might not be running (You can use the Cron Control plugin to check that). More likely there is a conflict with a third party plugin, possibly related to permissions as cron jobs are run as an unauthenticated user.

Unless you think PressForward is potentially conflicting with EO, I don't think there is a bug with PressForward.

That being the case, could you close this issue and open a question on the forums at https://wp-event-organiser.com/forums ? If you include what plugins you are running, if you were able to confirm that the crown job is running and lastly what exactly happens with the automatic sync that would be helpful.

**Comment by AramZS** [comment]
@stephenharris thanks!

**Comment by jeau** [comment]
@stephenharris 

Now I'm starting to understand a little more wp-cron ; 

I will investigate about my configuration and my installation. This site was in maintenance and quite inactive.  I think that before I see this problem synchronization was turned off. If this problem is confirmed then I will post on the forums of EO.

thanks
