### ISSUE TITLE
Tabs on tools page not working

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#946]
In WP versions 4.6 and older, the tabs on the tools pages are not functioning.

**Comment by jccatalano** [comment]
We had this problem before with issue #908

**Comment by AramZS** [comment]
This is because the pf object now requires the underlying javascript WP API object, introduced in 4.7. For anyone who runs PressForward earlier than 4.7 must install the WP REST API plugin or manually comment out that requirement and be prepared to deal with broken javascript functionality elsewhere. I'll make that dependency less impactful in this update, but it is still a dependency.

**Comment by jccatalano** [comment]
WordPress REST API (Version 2) does not work with WP versions 3.9 and older.
